### ISSUE TITLE
Man pages on completeopt previews are unformatted

### ISSUE THREAD

**Issue by otreblan** [josa42/coc-sh#20]
## Result from CocInfo
```
## versions             
                        
vim version: NVIM v0.4.0-1046-gd32b92e26    
node version: v11.15.0    
coc.nvim version: 0.0.71-9740746768    
term: rxvt-unicode-256color    
platform: linux         
                        
## Messages             
                        
## Output channel: snippets
```

## Describe the bug

Man page formatting is working on 'doHover'. But not in the coc-sh completeopt preview window.

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  autocmd CursorHold * silent call CocActionAsync('doHover')
  set updatetime=300
  let g:coc_global_extension = ["coc-sh"]
  set filetype=sh
  ```
- Create file `~/.config/nvim/coc-settings.json` with :
```
{
"suggest.enablePreview": true
}
```
- Start neovim with command: `nvim -u mini.vim`

- Type some program name and activate the preview floating window.

## Screenshots (optional)

![manFormating](https://user-images.githubusercontent.com/39320840/60035370-49329280-9672-11e9-9e20-286da4c24437.png)

**Comment by josa42** [comment]
@otreblan I am sorry for the late response. As I commented in neoclide/coc.nvim#911, I don't think this issue is caused by `coc-sh`.

Please reopen your original issue.

**Comment by josa42** [comment]
@otreblan Thank you for fixing this! (mads-hartmann/bash-language-server#162).
I updated `bash-language-server` to `v1.7.0` in `coc-sh` [`v0.4.0`](https://github.com/josa42/coc-sh/releases/tag/v0.4.0).
