### ISSUE TITLE
Language server taking long time to start

### ISSUE THREAD

**Issue by MCotocel** [josa42/coc-sh#50]
The language server takes about 45 seconds to start. It shows `Starting LS langaugeserver.bash`.

**Comment by 3nippo** [comment]
What about CPU usage during these 45 seconds? In my case it is about 100% during this 45 second startup. Maybe this issue and [this one](https://github.com/josa42/coc-sh/issues/53) are related?

**Comment by hejops** [comment]
In my case the language server seems to start within seconds, but CPU usage remains maxed out throughout the entire session.

**Comment by josa42** [comment]
Can't reproduce. Probably an issue with the bash-language-server  or coc.nvim
