### ISSUE TITLE
completion does not work for subcommands and arguments

### ISSUE THREAD

**Issue by Dragon-debian** [josa42/coc-sh#54]
I installed coc.nvim with neovim's builtin package manger, used the example configuration in the main page of the project.
Then I installed coc-sh with `:CocInstall coc-sh` inside neovim. but completion only works for commands, variables and paths (it doesnt work for hidden directories).

command pkg-config is available because package `pkg-config` is installed through apt. Im using debian 11. `bash-completion` package is installed.
I was installed coc.nvim and coc-sh on this system before, but there were no problem. I tried installing coc.nvim using an other user but result was the same.

I also tried installing coc.nvim through the vim-plug but it didnt work too.
The results are the same even when I use [bash-language-server](https://github.com/bash-lsp/bash-language-server) directly and configure coc.nvim to use that.

This is the output of `pkg-config --variable=datadir bash-completion`
```
/usr/share
```
and this is the output of `cat /usr/share/pkgconfig/bash-completion.pc`
```
prefix=/usr
datadir=/usr/share
sysconfdir=/etc

compatdir=${sysconfdir}/bash_completion.d
completionsdir=${datadir}/bash-completion/completions
helpersdir=${datadir}/bash-completion/helpers

Name: bash-completion
Description: programmable completion for the bash shell
URL: https://github.com/scop/bash-completion
Version: 2.11
```

**Comment by josa42** [comment]
> The results are the same even when I use bash-language-server directly and configure coc.nvim to use that.
Doesn't seem to be an issue with coc-sh 🤷🏼‍♂️
