### ISSUE TITLE
[coc.nvim] Server sh failed to start: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by homie-desktop** [josa42/coc-sh#57]
tried installing `coc-sh` and added the following to my coc-settings.json

```
  "languageserver": {
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    }
  },
```

but when opening `.sh` files, it outputs the following errors: 
```
[coc.nvim] Server sh failed to start: Error: spawn UNKNOWN
```

**Comment by josa42** [comment]
If you are configuring the language server like that, you are not using this package.

**Comment by erfan4323** [comment]
I have the same issue with cpp clangd files
but there is nothing to solve it
