### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by oblitum** [josa42/coc-sh#61]
Extension stopped working. Latest bash-language-server is at version 3, this extension is tied to version 2, maybe that's the cause.

**Comment by IngoMeyer441** [comment]
Perhaps, this issue could be relevant: <https://github.com/bash-lsp/bash-language-server/issues/353>.

**Comment by randallwc** [comment]
https://github.com/bash-lsp/bash-language-server/issues/353#issuecomment-1133847079
