### ISSUE TITLE
disable coc-sh for .bashrc

### ISSUE THREAD

**Issue by laoshaw** [josa42/coc-sh#69]
how to disable that, my bashrc is a large file and coc-sh made it really slow.

**Comment by josa42** [comment]
You could disable coc.nvim with an auto command:

```viml
autocmd BufNew,BufRead .bashrc CocDisable
```

Or add disable coc-sh for you home directory by adding this to the local config:

`~/.vim/coc-settings.json`
```json
{
  "sh.enable": false
}
```
