### ISSUE TITLE
`bashIde` settings not available

### ISSUE THREAD

**Issue by martin-braun** [josa42/coc-sh#74]
I can access `sh.*` settings, but not `bashIde.*` settings in the `coc-settings.json`:

<img width="591" alt="image" src="https://github.com/josa42/coc-sh/assets/24259245/72da2694-4213-41d5-9b3b-8dfd5649aad2">

Why is that please?

Background, some info messages are false positives, like in this example where I don't wish to resolve expressions? Why does this need to be printed?

<img width="731" alt="image" src="https://github.com/josa42/coc-sh/assets/24259245/29dcfd94-919d-4d40-984f-e90e85204d72">

This is just a ridiculous hint from ShellCheck. I know that and I don't want to get `$PATH` expanded in this case for obvious reasons. I guess I can just `# shellcheck disable=SC2016`, but it would be nice to just ignore any info statements.

**Comment by josa42** [comment]
Not sure what the issue is, it seems to work fine.

<img width="763" alt="image" src="https://github.com/josa42/coc-sh/assets/423234/62062812-0624-4541-876d-9da9233cfdc3">
